### ISSUE TITLE
mirror_example.py issue ?

### ISSUE THREAD

**Issue by al1138** [rbrcsk/pushbullet.py#142]
Hello,

when I try mirror_example.py, I get this error, and don't receive mirrored message : 
```
MIRROR
ERROR:root:[Errno 2] No such file or directory: 'notify-send'
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/pushbullet/listener.py", line 75, in on_message
    self.on_push(json_message)
  File "mirror_example.py", line 71, in watcher
    push["push"]["body"], image_path)
  File "mirror_example.py", line 78, in notify
    subprocess.Popen(["notify-send", title, body, "-i", image or ""])
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'notify-send'
```
Any idea ?

**Comment by rbrcsk** [comment]
Hey! You need the `notify-send` command in your path: https://ss64.com/bash/notify-send.html
